#spring.application.name=service-discovery

spring:
  application:
    name: SERVICE-DISCOVERY
#  security:
#    user:
#      name: eureka
#      password: password
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: '1.0'
logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


