server:
    port: 8053

spring:
  application:
      name: PRODUCT-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: product-service
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: '1.0'

logging:

  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

